
//---------------屏幕方向-------------
//获取屏幕方向 payload=LANDSCAPE|PORTRAIT|...
export const REFRESH_SCREEN_ORIENTATION="REFRESH_SCREEN_ORIENTATION"
//锁定屏幕方法 payload=LANDSCAPE|PORTRAIT|...
export const LOCK_SCREEN_ORIENTATION="LOCK_SCREEN_ORIENTATION"
//取消锁定屏幕
export const UNLOCK_SCREEN_ORIENTATION="UNLOCK_SCREEN_ORIENTATION"
//屏幕方向改变 payload=LANDSCAPE|PORTRAIT|...
export const ORIENTATION_CHANGE="ORIENTATIONS_CHANGE"
